### ISSUE TITLE
Launcher UI zoomed in

### ISSUE THREAD

**Issue by Emosewaj** [XLabsProject/launcher#242]
It seems that for some users, the launcher appears zoomed in. I suspect a DPI issue; Dss0 stated this as well:

> 刀丂丂〄 — 14.02.2022 18:26 UTC+1
> seems cef gets x and y coordinates of the window with (GetSystemMetrics(SM_CXSCREEN) which is not dpi aware

![20220214_174206](https://user-images.githubusercontent.com/16309996/153920941-c4277519-c7aa-4066-aaf8-4acfa00a17d4.jpg)
Depicted monitor: HP X27qc

Other affected monitors:
- Asus Tuf 1440
- VIOTEK GNV29CB Ultrawide
- LG 24MP400
- LG 27GL850

I'll add more information about affected monitors as I come upon cases.

### Workaround
The path can be entered manually in `%localappdata%\xlabs\user`:
```json
{"aw-install":"H:\\Games\\s1x_full_game","ghosts-install":"G:\\Games\\iw6x_full_game","mw2-install":"H:\\Games\\iw4x_full_game"}
```

### Note
Windows scaling does not cause nor prevent this issue.

**Comment by Dss0** [comment]
Fixed in #296

**Comment by Emosewaj** [comment]
This issue persists with a lot of people, reopening.
![Screenshot_20220823-174719](https://user-images.githubusercontent.com/16309996/186203375-fe44bcee-0203-4411-be16-6ba396e865b3.png)

**Comment by Rackover** [comment]
Related to this ? https://github.com/XLabsProject/launcher/commit/0d914b74739497fa420e10b79a500a890c4ffa5a
Not sure why the whole thing was reverted, there's not a lot of comment about it ☹

**Comment by Emosewaj** [comment]
@momo5502 Please elaborate

**Comment by momo5502** [comment]
shouldnt this be fixed?

**Comment by Rackover** [comment]
> https://github.com/XLabsProject/launcher/commit/0d914b74739497fa420e10b79a500a890c4ffa5a

did you not revert it completely ?

**Comment by momo5502** [comment]
> > https://github.com/XLabsProject/launcher/commit/0d914b74739497fa420e10b79a500a890c4ffa5a
> 
> did you not revert it completely ? 

Yes, and then I fixed it: a4cee99c1859b398849bd09d02d6355591808acb

**Comment by Rackover** [comment]
well apparently not 😄  either something changed in recent windows updates, or that chromium switch you removed was necessary, or your manual DPI MoveWindow calculation is doubling something windows already does, or it's something else!

this was fixed last time I touched it (as per testing on people who were affected by the problem) but i didn't look into it since, and to be fair wasn't even aware it had been reverted until very recently

**Comment by momo5502** [comment]
I'm using a high dpi monitor and it works fine for me. With Win11. That issue is pretty old. Older than the fix, are you sure that it's still an issue?

**Comment by Rackover** [comment]
Yea it used that we could trigger the issue simply by changing DPI settings in windows while the launcher was running, which would cause it - but that is no longer the case. However people still have the problem :
https://discord.com/channels/219514629703860235/1017078851194585108
https://discord.com/channels/219514629703860235/985571976527626252
https://discord.com/channels/219514629703860235/983076549030973451
Here are the last three examples I found

Back when before this bug was fixed the zoom used to be far greater than that, and I remember during fixing it that I found out basically the DPI was calculated thrice (once by chromium, once by you manually, once by windows) and that disabling both chromium's and yours would fix it for good as windows would handle it properly. Maybe now it's only handled twice, and either your code or chromium's adjustment is failing it? no idea, have not looked into it yet

**Comment by momo5502** [comment]
> Yea it used that we could trigger the issue simply by changing DPI settings in windows while the launcher was running, which would cause it - but that is no longer the case. However people still have the problem : https://discord.com/channels/219514629703860235/1017078851194585108 https://discord.com/channels/219514629703860235/985571976527626252 https://discord.com/channels/219514629703860235/983076549030973451 Here are the last three examples I found
> 
> Back when before this bug was fixed the zoom used to be far greater than that, and I remember during fixing it that I found out basically the DPI was calculated thrice (once by chromium, once by you manually, once by windows) and that disabling both chromium's and yours would fix it for good as windows would handle it properly. Maybe now it's only handled twice, and either your code or chromium's adjustment is failing it? no idea, have not looked into it yet

Hm, weird. Your fix broke it entirely tho for me. Currently it works perfectly fine for me. Starting it on any monitor will always yield perfect scaling. Moving it onto any window will work fine and even changing dpi at runtime also works. What kind of window scaling values do these guys use? Works fine for me with 125%, 150% and 175%

**Comment by momo5502** [comment]
Also, does applying the chromium flag fix it?

**Comment by Rackover** [comment]
i do not know i haven't looked into it (working on iw4x atm) but you should defo contact those people on discord and ask them, it's gonna be much easier than with an intermediate :P  Fortunately the chromium flag thingy is very easy to try, so it might just be that!

**Comment by Emosewaj** [comment]
I will go ahead and contact some affected people for that information. I will need them for testing anyway.

**Comment by TheoreticalThreat** [comment]
I'm glad I decided to search up this GitHub page, and I'm not alone on this issue. 

1920 x 1080 monitor, scaling set to 100%. I've tried at different scalings, I've tried changing the resolution, I've tried messing with related NVIDIA Control Panel settings, and I've tried on a different monitor with a higher resolution (and changing resolutions and scaling there). I also tried right-clicking on the launcher, clicking on Properties, then the Compatibility tab, and check marking "Disable Fullscreen Optimizations," as well as running it with Administrator Privilege. Nothing has worked.
